bernese/accounts/urls.py
# from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views
from bernese.accounts.forms import AuthenticationForm2
from .views import register, register_validator
from django.urls import reverse_lazy

app_name='accounts'

urlpatterns = [
    path('entrar/', views.LoginView.as_view(template_name='login.html',
                                            form_class=AuthenticationForm2,
                                            redirect_authenticated_user=True),
                    name='login'),

    path('sair/', views.LogoutView.as_view(next_page='core:index'), name='logout'),
    path('cadastrar/', register, name='register'),
    path('alterar-senha/',views.PasswordResetView.as_view(
                                            template_name='password_reset.html',
                                            success_url='ok/',
                                            email_template_name = 'password_reset_email.html'
                        ),name='password_reset'),
    path('nova-senha/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
                                            template_name='password_reset_confirm.html',
                                            success_url=reverse_lazy('accounts:password_reset_complete')
                        ), name='password_reset_confirm'),
    path('alterar-senha/ok/',views.PasswordResetDoneView.as_view(
                                            template_name='password_reset_done.html'
                        ),name='password_reset_done'),
    path('nova-senha/ok/',views.PasswordResetCompleteView.as_view(
                                            template_name='password_reset_complete.html'
                        ),name='password_reset_complete'),
    path('cadastrar/<uidb64>/<token>/', register_validator, name='register_validator'),

]

bernese/core/urls.py
#from django.conf.urls import url
from django.urls import path
from bernese.core.views import index, about, contact, monitor, tools, check, process_line_view

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('ferramentas/', tools, name='tools'),
    path('sobre/', about, name='about'),
    path('contato/', contact, name='contact'),
    path('monitoramento/', monitor, name='monitor'),
    path('check/',check, name='check'),
    path('fila/',process_line_view, name='process_line_view')

]

bernese/urls.py
# from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('controle/', admin.site.urls),
    path('', include('bernese.core.urls', namespace='core')),
    path('ppp/', include('bernese.ppp.urls', namespace='ppp')),
    path('relativo/', include('bernese.relativo.urls', namespace='relativo')),
    path('rapido/', include('bernese.rapido.urls', namespace='rapido')),
    path('rede/', include('bernese.rede.urls', namespace='rede')),
    path('conta/', include('bernese.accounts.urls', namespace='accounts')),
    path('favicon.ico',RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    path('robots.txt',RedirectView.as_view(url='/static/robots.txt',permanent=True)),
    path('apple-touch-icon-precomposed.png',RedirectView.as_view(url='/static/logo-gnss-ufv.png', permanent=True)),
    path('apple-touch-icon.png',RedirectView.as_view(url='/static/logo-gnss-ufv.png', permanent=True))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler500 = 'bernese.core.views.custom_error_500_view'

bernese/core/models.py
from django.db import models
from django.utils import timezone
from bernese.settings import RINEX_UPLOAD_TEMP_DIR


class Proc_Request(models.Model):

    METHOD_CHOICES = (
        ('ppp', 'PPP'),
        ('relativo', 'Relativo'),
        ('rede', 'Rede'),
        ('rapido', 'Rapido')
    )

    STATUS_CHOICES = (
        ('waiting', 'Aguardando'),
        ('running', 'Processando'),
        ('finished', 'Finalizado'),
    )

    # proc_id = models.CharField(primary_key=True, max_length=100) # not interesting
    proc_method = models.CharField('Método do Processamento',choices = METHOD_CHOICES, max_length=10)
    proc_status = models.CharField('Status do Processamento',choices = STATUS_CHOICES,default='waiting',max_length=10)
    email = models.EmailField('E-mail')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    started_at = models.DateTimeField('Iniciado em', null=True, blank=True)
    finished_at = models.DateTimeField('Finalizado em',null=True, blank=True)
    hoi_correction = models.BooleanField('Correção da Ionosfera de ordem superior',default=True)

    def __str__(self):
        return 'Process request id (' + str(self.id) + ')'

    def __rpr__(self):
        return 'Proc_Request id: ' + str(self.id)

    def start_process(self):
        self.proc_status = self.STATUS_CHOICES[1][0]                # 'running'
        self.started_at = timezone.localtime(timezone.now())
        self.save()

    def finish_process(self):
        self.proc_status = self.STATUS_CHOICES[2][0]                # 'finished'
        self.finished_at = timezone.localtime(timezone.now())
        self.save()

    def get_proc_details(self):
        if self.proc_method == 'ppp':
            from bernese.ppp.models import Details_PPP
            return Details_PPP.objects.get(pk=self.id)
        elif self.proc_method == 'relativo':
            from bernese.relativo.models import Details_Relativo
            return Details_Relativo.objects.get(pk=self.id)
        elif self.proc_method == 'rede':
            from bernese.rede.models import Details_Rede
            return Details_Rede.objects.get(pk=self.id)
        elif self.proc_method == 'rapido':
            from bernese.rapido.models import Details_Rapido
            return Details_Rapido.objects.get(pk=self.id)
        else:
            return None

    class Meta:
        verbose_name = 'Solicitação de Processamento'
        verbose_name_plural = 'Solicitações de Processamentos'
        ordering = ['-created_at']

#-------------------------------------------------------------------------------

TECTONIC_PLATE_CHOICES = (
    ('SOAM', 'SOAM - Sul-Americana',),
    ('AFRC', 'AFRC - Africa'),
    ('ANTA', 'ANTA - Antarctica'),
    ('ARAB', 'ARAB - Arabia'),
    ('AUST', 'AUST - Australia'),
    ('CARB', 'CARB - Caribbean'),
    ('COCO', 'COCO - Cocos (north of NAZC, south of NOAM, east of CARB)'),
    ('EURA', 'EURA - Eurasia'),
    ('INDI', 'INDI - India'),
    ('JUFU', 'JUFU - Juan de Fuca (in between northern NOAM and PCFC)'),
    ('NAZC', 'NAZC - Nazca (west of SOAM, east of PCFC)'),
    ('NOAM', 'NOAM - North America'),
    ('SOAM', 'SOAM - South America'),
    ('PCFC', 'PCFC - Pacific'),
    ('PHIL', 'PHIL - Philippine'),
)


#-------------------------------------------------------------------------------

class Coordinates(models.Model):

    X = models.FloatField()
    Y = models.FloatField()
    Z = models.FloatField()
    devX = models.FloatField()
    devY = models.FloatField()
    devZ = models.FloatField()
    epoch = models.FloatField()
    datum = models.CharField(max_length=100)
    station_name = models.CharField(max_length=100, null=True)

    def latlong(self):
        pass            # TODO: Transformar coordenada para latlong

    def UTM(self):
        pass            # TODO: Transformar coordenada para UTM (plan e alt)

    class Meta:
        verbose_name = 'Coordenada de Referência'
        verbose_name_plural = 'Coordenadas de Referência'



def basesRBMC(X,Y,Z,dist):

    query = '''SELECT *
                FROM rbmc,
                    ST_Transform(
                    ST_SetSRID(
                    ST_MakePoint({:12.8f},{:12.8f},{:12.8f}),4919),4326) AS ponto
                WHERE ST_Dwithin(rbmc.geom,ponto,{:d}000,true)'''.format(X,Y,Z,int(dist))

    query_set = Proc_Request.objects.raw(query)

    stations =[]
    for field in query_set:
        stations.append(field.name)

    return stations

bernese/core/forms.py
from django import forms
from django.conf import settings

class ContactGeneral(forms.Form):

	name = forms.CharField(
		label = 'Nome',
		widget = forms.TextInput(attrs={'class': 'form-control'})
		)

	email = forms.EmailField(
		label='Email',
		widget = forms.EmailInput(
			attrs={'class': 'form-control'}
				)
		)

	message = forms.CharField(
		label = 'Mensagem/Sugestão',
		widget = forms.Textarea(attrs={'class': 'form-control'})
		)

class BerneseTools(forms.Form):


	widget_content = {'class': 'form-control',
					  'type' : 'date',
					  'placeholder' : '06/01/1980',
					  }

	date = forms.DateField(
							label = 'Data do rastreio',
							widget = forms.DateInput(attrs=widget_content)
						  )

bernese/core/views.py
from django.shortcuts import render
from .forms import ContactGeneral, BerneseTools
from .mail import enviar_email
from django.http import HttpResponse
from datetime import datetime
import threading
from bernese.core.rinex import date2gpsWeek
from bernese.core.process_line import check_line
import requests
import os
from django.core.paginator import Paginator
from bernese.core.models import Proc_Request
from django.contrib.auth.decorators import login_required

def index(request):
	# return HttpResponse('Em manutenção!')
	template_name = 'index.html'
	context = {}
	context['isHome'] = True
	return render(request, template_name, context)

def tools(request):
	template_name = 'tools.html'
	context = {}
	context['fileList'] = []

	if request.method == 'POST':

		form = BerneseTools(request.POST)

		if form.is_valid():

			rnxDate = datetime.strptime(str(form.cleaned_data['date']),'%Y-%m-%d')

			weekDay = date2gpsWeek(rnxDate)

			if rnxDate.year > 1999:
				anoRed = rnxDate.year - 2000
			else:
				anoRed = rnxDate.year - 1900

			sClkFile = 'http://ftp.aiub.unibe.ch/CODE/{:04d}/COD{}.CLK.Z'.format(rnxDate.year,weekDay)
			sEphFile = 'http://ftp.aiub.unibe.ch/CODE/{:04d}/COD{}.EPH.Z'.format(rnxDate.year,weekDay)
			sIonFile = 'http://ftp.aiub.unibe.ch/CODE/{:04d}/COD{}.ION.Z'.format(rnxDate.year,weekDay)
			sErpFile = 'http://ftp.aiub.unibe.ch/CODE/{:04d}/COD{}.ERP.Z'.format(rnxDate.year,weekDay)
			sErpWFile = 'http://ftp.aiub.unibe.ch/CODE/{:04d}/COD{}7.ERP.Z'.format(rnxDate.year,weekDay[:4])
			sP1C1File = 'http://ftp.aiub.unibe.ch/CODE/{:04d}/P1C1{:02d}{:02d}.DCB.Z'.format(rnxDate.year,anoRed,rnxDate.month)
			sP1P2File = 'http://ftp.aiub.unibe.ch/CODE/{:04d}/P1P2{:02d}{:02d}.DCB.Z'.format(rnxDate.year,anoRed,rnxDate.month)

			sfileList = [sClkFile, sEphFile, sErpFile, sErpWFile, sIonFile, sP1C1File, sP1P2File]

			# Verifica se o arquivo existe, se não existir remove da lista
			for sfile in sfileList:
				link_file = requests.head(sfile)
				if link_file.status_code != 200:
					i = sfileList.index(sfile)
					sfileList[i] = ''          # Remove url invalida da lista

			context['codfilelist'] = sfileList[:4]
			context['bswfilelist'] = sfileList[4:]

	else:
		form = BerneseTools()

	context['form'] = form
	context['isTools'] = True
	return render(request, template_name, context)

# def ephem(request,date):
# 	template_name = 'ephem.html'
# 	context = {}
#
# 	date = datetime.strptime(date,'%Y-%m-%d')
#
#
#
# 	context['isTools'] = True
# 	return render(request, template_name, context)


def about(request):
	template_name = 'about.html'
	context = {}
	context['isAbout'] = True
	return render(request, template_name, context)

def contact(request):
	template_name = 'contact.html'
	context = {}
	if request.method == 'POST':
		form = ContactGeneral(request.POST)
		if form.is_valid():
			context['is_valid'] = True
			email_context = {
				'name' : form.cleaned_data['name'],
				'email' : form.cleaned_data['email'],
				'message' : form.cleaned_data['message'],
			}
			enviar_email(**email_context)
			form = ContactGeneral()
	else:
		form = ContactGeneral()

	context['form'] = form
	context['isContact'] = True
	return render(request, template_name, context)


def monitor(request):

	msg = 'Processamentos ativos: '
	nproc = 0
	for tr in threading.enumerate():
		# if tr.name[:4] == 'bern':
		msg += tr.name + ', '
		nproc += 1
	
	if not nproc: msg += 'Nenhum'

	return HttpResponse(msg)


def custom_error_500_view(request):
	template_name = '500.html'
	context = {}
	return render(request, template_name, context)


def check(request):
	check_line()
	return process_line_view(request)


@login_required
def process_line_view(request):

	threads = monitor(request).content.decode()

	proc_list = Proc_Request.objects.all()
	paginator = Paginator(proc_list, 100) # Show 100 per page
	page = request.GET.get('page')
	procs = paginator.get_page(page)

	proc_run = Proc_Request.objects.filter(proc_status = 'running')

	context = {
		'procs': procs,
		'proc_run' : proc_run,
		'isFila' : True,
		'threads' : threads
		}

	return render(request, 'proc_list.html', context)

bernese/core/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <div class="container theme-showcase" role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <p><h4>Sistema desenvolvido como parte do projeto de pesquisa cadastrado no
          <a target="_blank" href="https://www2.dti.ufv.br/sisppg/scripts/projetos/consultarProjeto.php">
          SisPPG
          </a>
          com número: 191085.
        </h4></p>
        <p><h4>Os dados GNSS são processados pelo
          <a target="_blank" href="http://www.bernese.unibe.ch">
          software Bernese GNSS
          </a>
           (versão 5.2) sob licença do departamento de Engenharia Civil da UFV.
        </h4></p>
        <p><h4>Se interessou pelo projeto? Acesse o código no
          <a target="_blank" href="https://github.com/gabriel-oliveira/gnss-ufv">
          GitHub
          </a>
          e contribua.
        </h4></p>
      </div>

    </div> <!-- /container -->
{% endblock %}

bernese/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
  <head>
    <meta charset="unicode">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Sistema de processamento de dados GNSS da UFV">
    <meta name="author" content="Gabriel Diniz de Oliveira">
    <title>GNSS-UFV</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'logo-gnss-ufv.png' %}"/>

    <!-- Custom styles for this template -->
    <link href="{% static 'home/home.css' %}" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'home/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'home/dist/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    {% comment %} <link href="{% static 'home/assets/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet"> {% endcomment %}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{% static 'assets/js/ie8-responsive-file-warning.js' %}"></script><![endif]-->
    {% comment %} <script src="{% static 'home/assets/js/ie-emulation-modes-warning.js' %}"></script> {% endcomment %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% comment %} CSS para a seleção das estações da RBMC em rede {% endcomment %}
      <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">

  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand logo">
          <span class="logo-u">GNSS-U</span><span class="logo-f">F</span><span class="logo-v">V</span>
          </a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li {% if isHome %} class="active"{% endif %}><a href="{% url 'core:index' %}">Início</a></li>
            <li {% if isPPP %} class="active"{% endif %}><a href="{% url 'ppp:index' %}">PPP</a></li>
            <li {% if isRelativo %} class="dropdown active" {% else %} class="dropdown" {% endif %}>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Relativo <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'relativo:index' %}">Linha de Base Única</a></li>
                <li><a href="{% url 'rede:index' %}">Linhas de Base Múltiplas</a></li>
                <li><a href="{% url 'rapido:index' %}">Estático Rápido</a></li>
              </ul>
            </li>
            <li {% if isFila %} class="active"{% endif %}><a href="{% url 'core:process_line_view' %}">Status</a></li>
            <li {% if isTools %} class="active"{% endif %}><a href="{% url 'core:tools' %}">Ferramentas</a></li>
            <li {% if isAbout %} class="active"{% endif %}><a href="{% url 'core:about' %}">Sobre</a></li>
            <li {% if isContact %} class="active"{% endif %}><a href="{% url 'core:contact' %}">Contato</a></li>
            {% if user.is_admin %}
            <li><a href="{% url 'admin:index' %}"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></a></li>
            {% endif %}
          </ul>
            <div align='right'>
            <ul class="nav navbar-right navbar-nav">
            {% if user.is_authenticated %}
            <li><a>Bem-vindo, {{ user.first_name }}!</a>
            <li><a href="{% url 'accounts:logout' %}">Sair</a>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
            {% endif %}
          </ul>
          </div>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

{% block content %}{% endblock %}

    <footer class="footer">
      <div class="container">
        <div class="text-muted">
          <p align = "center">
            <a class="hidden-xs" href="http://www.dec.ufv.br" target="_blank">
              <img src="{% static 'home/logo-dec-footer.png' %}"
              alt="Departamento de Engenharia Civil" align="left" height="30px">
            </a>
            Desenvolvimento: <a href="http://buscatextual.cnpq.br/buscatextual/visualizacv.do?metodo=apresentar&id=K4437655J2" target="_blank">
            Gabriel Diniz de Oliveira</a>
            /
            Coordenação: <a href="http://buscatextual.cnpq.br/buscatextual/visualizacv.do?metodo=apresentar&id=K4770936E9" target="_blank">
            William Rodrigo Dal Poz</a>
            <a class="hidden-xs" href="http://www.ufv.br" target="_blank">
              <img src="{% static 'home/logo-ufv-footer.png'%}"
              alt="Universidade Federal de Viçosa" align="right" height="30px">
            </a>
          </p>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> {% endcomment %}
    {% comment %} <script src="{% static 'home/assets/js/vendor/jquery.min.js' %}"></script> {% endcomment %}
    <script src="{% static 'home/jquery.min.js' %}"></script>
    <script src="{% static 'home/dist/js/bootstrap.min.js' %}"></script>
    {% comment %} <script src="{% static 'home/assets/js/docs.min.js' %}"></script> {% endcomment %}
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    {% comment %} <script src="{% static 'home/assets/js/ie10-viewport-bug-workaround.js' %}"></script> {% endcomment %}
    
    {% comment %} Script para inserir texto de ajuda{% endcomment %}
    <script src="{% static 'home/helpMessages.js' %}"></script>

  </body>
</html>

bernese/core/templates/contact.html
{% extends 'base.html' %}
{% block content %}
    <div class="container theme-showcase" role="main">
      <h2>Entre em contato:</h2>
      <h4>Sugestões serão sempre bem vindas:</h4>
      <br>
      {% if is_valid %}
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          Mensagem enviada com sucesso!
        </div>
      {% endif %}
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
          {{ field.label_tag }}
          {{ field }}
          {% if field.errors %}
          <ul class="list-group">
            {% for erro in field.errors %}
            <li class="list-group-item list-group-item-danger">{{ erro }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-default btn-lg">Enviar</button>
      </form>
    </div> <!-- /container -->
{% endblock %}

bernese/core/templates/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
<p><strong>Menssagem</strong>:</p>
{{ message|linebreaks }}

bernese/core/templates/index.html
{% extends 'base.html' %}
{% block content %}



    <div class="container theme-showcase" role="main">

      <!-- <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        Sistema em Manutenção!!!
      </div> -->

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1 class="logo">
          <span class="logo-u">GNSS-U</span><span class="logo-f">F</span><span class="logo-v">V</span>
        </h1>
        <h2>Sistema de processamento de dados GNSS da UFV.</h2>
        <h4>Sistema de processamento de dados GNSS com fins científicos e/ou
          acadêmicos destinado aos usuários da Universidade Federal de Viçosa.</h4>
      </div>

    </div> <!-- /container -->
{% endblock %}

bernese/core/templates/manutencao.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
  <head>
    <meta charset="unicode">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Template Base do GNSS-UFV">
    <meta name="author" content="Gabriel">

    <title>GNSS-UFV</title>

    <!-- Custom styles for this template -->
    <link href="{% static 'home/home.css' %}" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'home/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'home/dist/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'home/assets/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{% static 'assets/js/ie8-responsive-file-warning.js' %}"></script><![endif]-->
    <script src="{% static 'home/assets/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand"><font color="black">GNSS-UFV</font></a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container theme-showcase" role="main">

	<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
    Em Manutenção! <br> Previsão de retorno 22/03/2018 18:00
  </div>
      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1><font color="black">GNSS-UFV</font></h1>
        <p>Sistema de processamento de dados GNSS da UFV.</p>
      </div>

    </div> <!-- /container -->


    <footer class="footer">
      <div class="container">
        <div class="text-muted">
          <p align = "center">
            <a class="hidden-xs" href="http://www.dec.ufv.br" target="_blank">
              <img src="{% static 'home/logo-dec-footer.png' %}"
              alt="Departamento de Engenharia Civil" align="left" height="30px">
            </a>
            Desenvolvimento: <a href="http://buscatextual.cnpq.br/buscatextual/visualizacv.do?metodo=apresentar&id=K4437655J2" target="_blank">
            Gabriel Diniz de Oliveira</a>
            /
            Coordenação: <a href="http://buscatextual.cnpq.br/buscatextual/visualizacv.do?metodo=apresentar&id=K4770936E9" target="_blank">
            William Rodrigo Dal Poz</a>
            <a class="hidden-xs" href="http://www.ufv.br" target="_blank">
              <img src="{% static 'home/logo-ufv-footer.png'%}"
              alt="Universidade Federal de Viçosa" align="right" height="30px">
            </a>
          </p>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'home/assets/js/vendor/jquery.min.js' %}"></script>
    <script src="{% static 'home/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/assets/js/docs.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'home/assets/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

bernese/core/templates/result_email.html
{{ message|linebreaks }}