bernese/rede/urls.py
# from django.conf.urls import url
from django.urls import path
from bernese.rede.views import index

app_name='rede'

urlpatterns = [
    path('', index, name='index'),
]

bernese/urls.py
# from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('controle/', admin.site.urls),
    path('', include('bernese.core.urls', namespace='core')),
    path('ppp/', include('bernese.ppp.urls', namespace='ppp')),
    path('relativo/', include('bernese.relativo.urls', namespace='relativo')),
    path('rapido/', include('bernese.rapido.urls', namespace='rapido')),
    path('rede/', include('bernese.rede.urls', namespace='rede')),
    path('conta/', include('bernese.accounts.urls', namespace='accounts')),
    path('favicon.ico',RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    path('robots.txt',RedirectView.as_view(url='/static/robots.txt',permanent=True)),
    path('apple-touch-icon-precomposed.png',RedirectView.as_view(url='/static/logo-gnss-ufv.png', permanent=True)),
    path('apple-touch-icon.png',RedirectView.as_view(url='/static/logo-gnss-ufv.png', permanent=True))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler500 = 'bernese.core.views.custom_error_500_view'

bernese/rede/models.py
from bernese.core.models import *


def get_basesRBMC():
    
    query = 'SELECT * FROM rbmc'
    query_set = Proc_Request.objects.raw(query)

    stations =[]
    for field in query_set:
        stations.append((field.name,field.name))

    return tuple(stations)


class Details_Rede(Proc_Request):

    def save(self, *args, **kwargs):
        self.proc_method = 'rede'
        super().save(*args, **kwargs)

    COORD_REF_CHOICES = (
        ('header_rinex', 'Cabeçalho do Rinex'),
        ('user_set','Informado pelo usuário'),
    )

    BASE_DEFINITION = (
        ('auto', 'Automática'),
        ('manual','Manual'),
    )

    base_select_max_distance = models.IntegerField('Distânca Máxima das bases', default='200', null=True, blank=True)
    bases_rbmc_choices = models.CharField('Estações da RBMC', null=True, blank=True, max_length=1000)
    base_select_type = models.CharField('Seleção das bases', choices=BASE_DEFINITION, default='auto', max_length=10)
    rinex_rover_file= models.FileField(max_length=256)
    tectonic_plate_base = models.CharField('Placa Tectonica da Estação Base', choices=TECTONIC_PLATE_CHOICES, default='SOAM', max_length=5)
    tectonic_plate_rover = models.CharField('Placa Tectonica da Estação Rover', choices=TECTONIC_PLATE_CHOICES, default='SOAM', max_length=5)
    blq_file =  models.FileField(max_length=256, null=True, blank=True)
    coord_ref_type = models.CharField('Origem das coordenadas de referência', choices=COORD_REF_CHOICES, default='header_rinex',max_length=20)
    bases_rbmc = models.CharField('Bases da RBMC selecionadas', max_length=1000, null=True, blank=True)

    class Meta:
        verbose_name = 'Detalhes do Processamento Relativo em Rede'
        verbose_name_plural = 'Detalhes dos Processamentos Relativo em Rede'

bernese/rede/forms.py
from django import forms
from bernese.rede.models import Details_Rede, get_basesRBMC
from bernese.core.models import basesRBMC
from bernese.core.utils import is_blq
from bernese.core.rinex import isRinex, readRinexObs
from zipfile import ZipFile, is_zipfile
from django.core.files.storage import default_storage
from bernese.core.tasks import task_run_next


class redeRelativo(forms.ModelForm):

	# Verificando os dados contidos no campo rinex_rover_file inserido no formulario
	def clean_rinex_rover_file(self):
		rfile = self.cleaned_data['rinex_rover_file']
		(r_isOK,erroMsg) = isRinex(rfile)

		if is_zipfile(rfile):
			with ZipFile(rfile) as zfile:
				for file in zfile.namelist():
					with zfile.open(file) as rzfile:
						(r_isOK,erroMsg) = isRinex(rzfile)
					if not r_isOK: raise forms.ValidationError(erroMsg)

		if r_isOK:
			return rfile
		else:
			raise forms.ValidationError(erroMsg)

	# Verificando os dados contidos no campo blq_file inserido no formulario
	def clean_blq_file(self):
		bfile = self.cleaned_data['blq_file']
		if bfile:
			(b_ok,erroMsg) = is_blq(bfile)
			if b_ok:
				return bfile
			else:
				raise forms.ValidationError(erroMsg)

	def clean(self):
		cleaned_data = super().clean()

		rfile = cleaned_data.get('rinex_rover_file')

		headers= []

		if not rfile:
			f_isOK = False
			erroMsg = 'Arquivo invalido.'
		elif is_zipfile(rfile):
			# verifica se os arquivos compactados são validos
			with ZipFile(rfile) as zfile:
				for file in zfile.namelist():
					with zfile.open(file) as rzfile:
						(f_isOK, erroMsg, header) = readRinexObs(rzfile)
					if not f_isOK: raise forms.ValidationError(erroMsg)
					else: headers.append(header)
		else:
			(f_isOK, erroMsg, header) = readRinexObs(rfile)
			headers = [header]

		if not f_isOK:
			 raise forms.ValidationError(erroMsg)

		self.bases = {}

		for header in headers:
			# # Verificando o nome das estações
			if not header['MARKER NAME']:
				erroMsg = 'Favor definir o nome da estação do arquivo '
				erroMsg += header['RAW_NAME']
				raise forms.ValidationError(erroMsg)

			# # Verificando as coordenadas aproximadas
			coord_X = 0
			coord_Y = 0
			coord_Z = 0
			if self.cleaned_data['coord_ref_type'] == 'header_rinex':
				coord_X = float(header['APPROX POSITION XYZ'][0])
				coord_Y = float(header['APPROX POSITION XYZ'][1])
				coord_Z = float(header['APPROX POSITION XYZ'][2])

			if (not coord_X or not coord_Y or not coord_Z):
				 raise forms.ValidationError(
				 	'Favor definir as coordenadas aproximadas da estação no arquivo ' + header['RAW_NAME'])

			# Pré-seleção das bases da RBMC (Validação da existencia do arquivo na API do Bernese)
			bases_names = ''
			if self.cleaned_data['base_select_type'] == 'auto':
				bases = basesRBMC(coord_X,coord_Y,coord_Z,cleaned_data['base_select_max_distance'])
			elif self.cleaned_data['base_select_type'] == 'manual':
				bases = cleaned_data['bases_rbmc_choices'].replace(" ","").replace("'","").replace('[','').replace(']','').split(',') 
			
			for base in bases:
				if base != header['MARKER NAME']:
					bases_names += base
					bases_names += ' '

			if bases_names:
				self.bases[header['RAW_NAME']] = bases_names
			else:
				raise forms.ValidationError(
				'Não foram encontradas bases da RBMC para o arquivo ' + header['RAW_NAME'] +
				' em um raio de {}km'.format(cleaned_data['base_select_max_distance']))


	def save(self, *args, **kwargs):

		rfile = self.cleaned_data['rinex_rover_file']

		if is_zipfile(rfile):

			bfile = self.cleaned_data['blq_file']
			if bfile:
				bfile_newname = default_storage.save(bfile.name,bfile)
			else:
				bfile_newname = ''

			# uma nova instancia de solicitação de processamento para cada arquivo compactado
			with ZipFile(rfile) as zfile:
				for file in zfile.namelist():
					with zfile.open(file) as rzfile:
						rfile_name = default_storage.save(rzfile.name,rzfile)
					context = {
						'email' : self.cleaned_data['email'],
						'tectonic_plate_rover' : self.cleaned_data['tectonic_plate_rover'],
						'tectonic_plate_base' : self.cleaned_data['tectonic_plate_base'],
						'blq_file' :  bfile_newname,
						'rinex_rover_file' : rfile_name,
						'hoi_correction' : self.cleaned_data['hoi_correction'],
						'base_select_type' :  self.cleaned_data['base_select_type'],
						'base_select_max_distance' :  self.cleaned_data['base_select_max_distance'],
						'coord_ref_type' :  self.cleaned_data['coord_ref_type'],
						'bases_rbmc' : self.bases[file],
					}
					md = Details_Rede(**context)
					md.save()
					task_run_next.apply_async(task_id=str(md.pk))# Envio para o celery

		else:
			f = super().save(*args, **kwargs, commit=False)
			f.bases_rbmc = self.bases[rfile.name]
			f.save()
			task_run_next.apply_async(task_id=str(f.pk))  # Envio para o celery



	datum = forms.ChoiceField(
		label = 'Sistema de Referência',
		required = True,
		choices = (
			('ITRF2014', 'ITRF2014'),
			('ITRF2008', 'ITRF2008'),
			('ITRF2005', 'ITRF2005'),
			('ITRF2000', 'ITRF2000'),
			('SIRGAS2000', 'SIRGAS2000'),
			('IGS14', 'IGS14'),
			('IGS08', 'IGS08'),
			('IGb08', 'IGb08'),
			('IGS05', 'IGS05'),
			('IGS_00', 'IGS00'),
		),
		initial = 'SIRGAS2000',
		widget=forms.Select(
			attrs={'class': 'form-control'},
			)
	)

	epoch = forms.FloatField(
		label = 'Época das Coordenadas',
		required = True,
		initial = 2000.4,
		widget=forms.NumberInput(
			attrs={'class': 'form-control'},
			)
	)

	coord_X = forms.DecimalField(
		label = ' X (m)',
		max_digits = 15,
		decimal_places = 6,
		required = False,
		widget = forms.NumberInput(
			attrs = {'class': 'form-control'}
			)
		)

	coord_Y = forms.DecimalField(
		label = 'Y (m)',
		max_digits = 15,
		decimal_places = 6,
		required = False,
		widget = forms.NumberInput(
			attrs = {'class': 'form-control'}
			)
		)

	coord_Z = forms.DecimalField(
		label = 'Z (m)',
		max_digits = 15,
		decimal_places = 6,
		required = False,
		widget = forms.NumberInput(
			attrs = {'class': 'form-control'}
			)
		)

	class Meta:
		model = Details_Rede
		fields = (
			'email', 'rinex_rover_file', 'base_select_type', 'base_select_max_distance', 
			'bases_rbmc_choices', 'tectonic_plate_base', 'tectonic_plate_rover',
			'blq_file', 'hoi_correction', 'coord_ref_type', #'coord_ref'
			)
		widgets = {
			'email': forms.EmailInput(attrs={'class': 'form-control'}),
			'rinex_rover_file': forms.ClearableFileInput(attrs={'class': 'form-control'}),
			'base_select_type': forms.RadioSelect(attrs={'class': 'list-group'}),
			'base_select_max_distance' : forms.NumberInput(attrs={'class': 'form-control'}),
			'bases_rbmc_choices': forms.SelectMultiple(attrs={
				'class': 'form-control chosen-select-no-results',
				'data-placeholder': 'Buscar Estação'},
				choices=get_basesRBMC(),
				),
			'tectonic_plate_base': forms.Select(attrs={'class': 'form-control'}),
			'tectonic_plate_rover': forms.Select(attrs={'class': 'form-control'}),
			'blq_file': forms.ClearableFileInput(attrs={'class': 'form-control'}),
			'coord_ref_type' : forms.RadioSelect(attrs={'class': 'list-group'}),

		}
		labels = {
			'email' : 'E-mail',
			'rinex_rover_file' : 'Arquivo Rinex de Observação do ROVER',
			'base_select_type': 'Seleção das estações de referência (BASE)',
			'base_select_max_distance' : 'Raio máximo de distância para seleção das BASES (KM)',
			'bases_rbmc_choices': 'Selecione as estações de referência da RBMC',
			'tectonic_plate_base' : 'Selecione a placa tectônica das estações BASE',
			'tectonic_plate_rover' : 'Selecione a placa tectônica das estações ROVER',
			'blq_file' : 'Arquivo BLQ (Ocean Tide Loading)',
			'coord_ref_type' : 'Coordenadas de referência (BASE)',
			'hoi_correction' : 'Correção dos efeitos ionosféricos de ordem superior',
		}

bernese/rede/views.py
from django.shortcuts import render
from .forms import redeRelativo
from bernese.core.process_line import check_line
from django.contrib.auth.decorators import login_required
import requests

@login_required
def index(request):
	template_name = 'rede/index.html'
	context = {}
	erroMsg = 'Erro(s):'
	context['isRelativo'] = True

	if request.method == 'POST':

		form = redeRelativo(request.POST, request.FILES)

		if form.is_valid():

			form.save()

			context['isOK'] = True  # retorno ao usuario de solicitação enviada com sucesso
			form = redeRelativo() # Novo formulário em branco

		else:

			context['isErro'] = True
			context['erroMsg'] = erroMsg

	else:

		form = redeRelativo() # Novo formulário em branco

	context['form'] = form

	return render(request, template_name, context)

bernese/rede/templates/rede/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <div class="container theme-showcase" role="main">

        <div class="alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          Aplicação em teste.
        </div>

      <div class="alert alert-success alert-dismissible" role="alert" tabindex="0" id="uploadAlert" style="display:None">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        Aguarde o upload do arquivo!
      </div>

      <h2>Posicionamento Relativo- Linhas de Base Múltiplas</h2>

      <div align="right">
      <button id="helpCollapse-btn" class="btn btn-default" type="button" data-toggle="collapse" data-target="#helpCollapse" aria-expanded="false" aria-controls="helpCollapse">
        Descrição<span class="glyphicon glyphicon-question-sign help-icon"> </span>
      </button>
      </div>

      <div class="collapse" id="helpCollapse">
        <div class="well text-justify">
          <p>Neste modo são utilizadas múltiplas estações de referência (Base) pertencentes à Rede Brasileira 
de Monitoramento Continuas dos Sistemas GNSS, para determinar as coordenadas de uma única estação (Rover).</p>
          <div align="center" style="margin:20px"><img src="/static/home/multiple.png" class="img-responsive" alt="Método relativo para múltiplas linhas de base" with="320px"></img></div>
          <p>Para este modo são esperados arquivos com mais de duas horas de rastreio. </p>
          <p>Caso ocorra ‘erro’ no processamento a partir de arquivos submetidos com menos de duas horas de rastreio,
 é aconselhado que estes sejam processados no modo estático rápido.</p>
        </div>
      </div>

      {% if isOK %}
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          Arquivo submetido com sucesso!<br>O resultado do processamento será encaminhado por email.
        </div>
      {% endif %}
      {% if isErro or form.non_field_errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ erroMsg }}
          {{ form.non_field_errors }}
        </div>
      {% endif %}

      <form method="post" enctype="multipart/form-data" id="redeForm">
        {% csrf_token %}

        {% for field in form %}

        <div class="form-group">

          {% if field.html_name == "base_select_type" %}

            <label for="id_base_select_type_0">Seleção das estações de referência (BASE):</label>
            <a><span class="glyphicon glyphicon-question-sign help-icon" data-helpid="{{ field.html_name }}" data-helptitle="{{ field.label }}" data-toggle="modal" data-target="#helpModal" aria-hidden="true"></a>
            <ul id="id_base_select_type" class="list-group">
              <li class="list-group-item">
                <label for="id_base_select_type_0">
                <input class="list-group" type="radio" name="base_select_type"
                value="auto" required checked id="id_base_select_type_0"
                onclick="
                  document.getElementById('id_bases_rbmc_choices_chosen').disabled=true;
                  document.getElementById('id_bases_rbmc_choices').required=false;
                  document.getElementById('id_base_select_max_distance').disabled=false;
                  document.getElementById('id_base_select_max_distance').required=true;"
                >
                Automática (RBMC)
              </label>
              <a><span class="glyphicon glyphicon-question-sign help-icon" data-helpid="{{ field.html_name }}_auto" data-helptitle="Automática (RBMC)" data-toggle="modal" data-target="#helpModal" aria-hidden="true"></a>

              </li>
              <li class="list-group-item"><label for="id_base_select_type_1">
                <input type="radio" name="base_select_type" value="manual" id="id_base_select_type_1"
                onclick="
                  document.getElementById('id_bases_rbmc_choices_chosen').disabled=false;
                  document.getElementById('id_bases_rbmc_choices').required=true;
                  document.getElementById('id_base_select_max_distance').disabled=true;
                  document.getElementById('id_base_select_max_distance').required=false;"
                >
                Manual</label>
                <a><span class="glyphicon glyphicon-question-sign help-icon" data-helpid="{{ field.html_name }}_manual" data-helptitle="Manual" data-toggle="modal" data-target="#helpModal" aria-hidden="true"></a>

              </li>
            </ul>


            {% elif field.html_name == "coord_ref_type" %}

              <label for="id_coord_ref_type_0">Coordenadas de referência (BASE):</label>
              <a><span class="glyphicon glyphicon-question-sign help-icon" data-helpid="{{ field.html_name }}" data-helptitle="{{ field.label }}" data-toggle="modal" data-target="#helpModal" aria-hidden="true"></a>
              <ul id="id_coord_ref_type" class="list-group">
                <li class="list-group-item">
                  <label for="id_coord_ref_type_0">
                  <input class="list-group" type="radio" name="coord_ref_type"
                         value="header_rinex" required checked id="id_coord_ref_type_0">
                  No cabeçalho do arquivo rinex
                </label>
                <a><span class="glyphicon glyphicon-question-sign help-icon" data-helpid="{{ field.html_name }}_header_rinex" data-helptitle="No cabeçalho do arquivo rinex" data-toggle="modal" data-target="#helpModal" aria-hidden="true"></a>

                </li>
                <li class="list-group-item">
                <label for="id_coord_ref_type_1">
                  <input type="radio" name="coord_ref_type" value="user_set"
                         disabled=True id="id_coord_ref_type_1">
                  Inserir manualmente
                </label>
                <a><span class="glyphicon glyphicon-question-sign help-icon" data-helpid="{{ field.html_name }}_user_set" data-helptitle="Inserir manualmente" data-toggle="modal" data-target="#helpModal" aria-hidden="true"></a>

                </li>
              </ul>

           {% elif field.html_name in '["coord_X", "coord_Y", "coord_Z"]' %}
          <!-- campos criados manualmente no final do looping -->
          {% else %}
            {{ field.label_tag }}
            
              {% if field.html_name != "email" %}
                <a>
                <span class="glyphicon glyphicon-question-sign help-icon" data-helpid="{{ field.html_name }}" data-helptitle="{{ field.label }}" data-toggle="modal" data-target="#helpModal" aria-hidden="true">
                </a>
              {% endif %}

            {{ field }}

          {% endif %}

          {% if field.errors %}
          <ul class="list-group">
            {% for erro in field.errors %}
            <li class="list-group-item list-group-item-danger">{{ erro }}</li>
            {% endfor %}
          </ul>
          {% endif %}

        </div>
        {% endfor %}

        <!-- coordenadas de referencia -->
        <div class="form-group">
            <div class="row">
              <div class="col-sm-12">

                  <div class="input-group">
                  <span class="input-group-addon">X (m):</span>
                  <input type="number" step = "0.000001" max="999999999" min="-999999999" name="coord_X" class="form-control" disabled="" id="id_coord_X">
                  <span class="input-group-addon">Desvio X (m):</span>
                  <input type="number" step = "0.000001" max="999999999" min="-999999999" name="coord_dX" class="form-control" disabled="" id="id_coord_dX">
                  </div>
                  <div class="input-group">
                  <span class="input-group-addon">Y (m):</span>
                  <input type="number" step = "0.000001" max="999999999" min="-999999999" name="coord_Y" class="form-control" disabled="" id="id_coord_Y">
                  <span class="input-group-addon">Desvio Y (m):</span>
                  <input type="number" step = "0.000001" max="999999999" min="-999999999" name="coord_dY" class="form-control" disabled="" id="id_coord_dY">
                  </div>
                  <div class="input-group">
                  <span class="input-group-addon">Z (m):</span>
                  <input type="number" step = "0.000001" max="999999999" min="-999999999" name="coord_Z" class="form-control" disabled="" id="id_coord_Z">
                  <span class="input-group-addon">Desvio Z (m):</span>
                  <input type="number" step = "0.000001" max="999999999" min="-999999999" name="coord_dZ" class="form-control" disabled="" id="id_coord_dZ">
                  </div>

                  <br>
              </div><!-- /.col-lg-12 -->
            </div><!-- /.row -->
          </div><!-- /.form-group -->


          <button type="submit" class="btn btn-default btn-lg" onclick="
            if(document.getElementById('redeForm').checkValidity()){
              document.getElementById('uploadAlert').style.display='block';
              document.getElementById('uploadAlert').focus();
            }">
            Enviar
          </button>

        <script src="{% static 'chosen/docsupport/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'chosen/chosen.jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'chosen/docsupport/prism.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'chosen/docsupport/init.js' %}" type="text/javascript" charset="utf-8"></script>

      </form>
    </div> <!-- /container -->

<div class="modal fade" id="helpModal" tabindex="-1" role="dialog" aria-labelledby="helpModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span class="modal-title"></span>
      </div>
      <div class="modal-body text-justify">
        <span id="modal-message"></span>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}