bernese/accounts/urls.py
# from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views
from bernese.accounts.forms import AuthenticationForm2
from .views import register, register_validator
from django.urls import reverse_lazy

app_name='accounts'

urlpatterns = [
    path('entrar/', views.LoginView.as_view(template_name='login.html',
                                            form_class=AuthenticationForm2,
                                            redirect_authenticated_user=True),
                    name='login'),

    path('sair/', views.LogoutView.as_view(next_page='core:index'), name='logout'),
    path('cadastrar/', register, name='register'),
    path('alterar-senha/',views.PasswordResetView.as_view(
                                            template_name='password_reset.html',
                                            success_url='ok/',
                                            email_template_name = 'password_reset_email.html'
                        ),name='password_reset'),
    path('nova-senha/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
                                            template_name='password_reset_confirm.html',
                                            success_url=reverse_lazy('accounts:password_reset_complete')
                        ), name='password_reset_confirm'),
    path('alterar-senha/ok/',views.PasswordResetDoneView.as_view(
                                            template_name='password_reset_done.html'
                        ),name='password_reset_done'),
    path('nova-senha/ok/',views.PasswordResetCompleteView.as_view(
                                            template_name='password_reset_complete.html'
                        ),name='password_reset_complete'),
    path('cadastrar/<uidb64>/<token>/', register_validator, name='register_validator'),

]

bernese/urls.py
# from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('controle/', admin.site.urls),
    path('', include('bernese.core.urls', namespace='core')),
    path('ppp/', include('bernese.ppp.urls', namespace='ppp')),
    path('relativo/', include('bernese.relativo.urls', namespace='relativo')),
    path('rapido/', include('bernese.rapido.urls', namespace='rapido')),
    path('rede/', include('bernese.rede.urls', namespace='rede')),
    path('conta/', include('bernese.accounts.urls', namespace='accounts')),
    path('favicon.ico',RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    path('robots.txt',RedirectView.as_view(url='/static/robots.txt',permanent=True)),
    path('apple-touch-icon-precomposed.png',RedirectView.as_view(url='/static/logo-gnss-ufv.png', permanent=True)),
    path('apple-touch-icon.png',RedirectView.as_view(url='/static/logo-gnss-ufv.png', permanent=True))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler500 = 'bernese.core.views.custom_error_500_view'

bernese/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):

    def create_user(self, email, first_name, last_name, matricula, password, observacao):

        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            matricula=matricula,
            observacao=observacao,
        )

        user.is_active = False
        user.is_admin = False

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, first_name, password, observacao):

        user = self.create_user(
            email,
            password=password,
            first_name=first_name,
            last_name=' ',
            matricula=' ',
            observacao=observacao,
        )

        user.is_active = True
        user.is_admin = True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser):
    email = models.EmailField(verbose_name='E-mail',max_length=255,unique=True)
    first_name = models.CharField('Nome',max_length=255)
    last_name = models.CharField('Sobrenome',max_length=255,blank=True,null=True)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    matricula = models.CharField('Matrícula UFV',max_length=30,blank=True,null=True)
    observacao = models.TextField('Observação/Justificativa')

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','observacao']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'
        ordering = ['email']

bernese/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from .models import MyUser

class AuthenticationForm2(AuthenticationForm):
    username = UsernameField(
        label="E-mail",
        widget=forms.EmailInput(attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(
        label="Senha",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        )


class MyUserCreationForm(UserCreationForm):

    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirmação da Senha', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        if MyUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Este e-mail já está cadastrado.')
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Confirmação de senha não confere!")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


    class Meta(UserCreationForm.Meta):
        model = MyUser
        fields = ('email', 'first_name', 'last_name', 'matricula', 'password1', 'password2','observacao')
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'matricula': forms.TextInput(attrs={'class': 'form-control'}),
            # 'password1': forms.TextInput(attrs={'class': 'form-control'}),
            # 'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
            'observacao': forms.Textarea(attrs={'class': 'form-control', 'placeholder':
            'Decreva acerca de seu interesse pelo sistema.'}),
        }

bernese/accounts/views.py
from django.shortcuts import render
from .forms import MyUserCreationForm
from .utils import send_newuser_mail, register_validator as register_isValid
from django.http import HttpResponse

def register(request):
    template_name = 'register.html'
    isSuccess = False

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            usermail = form.cleaned_data['email']

            # envia e-mail para os administradores com botão (link) para validar cadastro
            send_newuser_mail(usermail, request)

            form = MyUserCreationForm()
            isSuccess = True

    else:
        form = MyUserCreationForm()
        isSuccess = False

    context = {
        'form' : form,
        'isSuccess' : isSuccess
    }

    return render(request, template_name, context)

def register_validator(request,uidb64,token):
    template_name = 'register_validator.html'
    context = {
        'isSuccess' : register_isValid(uidb64,token)
    }
    return render(request, template_name, context)

bernese/accounts/templates/login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container theme-showcase" role="main">
  {% if next %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      O usuário precisa estar autenticado para acessar esta aplicação.
    </div>
  {% endif %}
  <div class="jumbotron">
  {% if isErro or form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ erroMsg }}
      {{ form.non_field_errors }}
    </div>
  {% endif %}
  <form method="post" enctype="multipart/form-data" id="loginForm">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
      {{ field.label_tag }}
      {{ field }}
      {% if field.errors %}
      <ul class="list-group">
        {% for erro in field.errors %}
        <li class="list-group-item list-group-item-danger">{{ erro }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-default btn-lg">
      Entrar
    </button>
  </form>
  <br>
  <br>
<p style="font-size:15px;">
  Não é cadastrado? <a href="{% url 'accounts:register' %}">Cadastre-se</a> <br>
  Esqueceu a senha? <a href="{% url 'accounts:password_reset' %}">Nova senha</a>
</p>

  </div>
</div> <!-- /container -->

{% endblock %}

bernese/accounts/templates/password_reset.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container theme-showcase" role="main">
  <div class="jumbotron">
  {% if isErro or form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ erroMsg }}
      {{ form.non_field_errors }}
    </div>
  {% endif %}

  <form method="post" enctype="multipart/form-data" id="loginForm">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
      {{ field.label_tag }}
      {{ field }}
      {% if field.errors %}
      <ul class="list-group">
        {% for erro in field.errors %}
        <li class="list-group-item list-group-item-danger">{{ erro }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-default btn-lg">
      Enviar
    </button>
  </form>
  </div>
</div> <!-- /container -->

{% endblock %}

bernese/accounts/templates/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
<div class="container theme-showcase" role="main">
  <div class="jumbotron">
<p>{{ title }}</p>
<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>
</div>
</div>
{% endblock %}

bernese/accounts/templates/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
<div class="container theme-showcase" role="main">
  <div class="jumbotron">

<h2>{{ title }}</h2>

{% if validlink %}

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-password1">
        {{ form.new_password1.errors }}
        <label for="id_new_password1">{% trans 'New password:' %}</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-row field-password2">
        {{ form.new_password2.errors }}
        <label for="id_new_password2">{% trans 'Confirm password:' %}</label>
        {{ form.new_password2 }}
    </div>
    <input type="submit" value="{% trans 'Change my password' %}">
</fieldset>
</form>

{% else %}

<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

</div>
</div>

{% endblock %}

bernese/accounts/templates/password_reset_done.html
{% load i18n %}

{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

<p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>

{% endblock %}

bernese/accounts/templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

bernese/accounts/templates/register.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container theme-showcase" role="main">
  <div class="jumbotron">
  {% if isErro or form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ erroMsg }}
      {{ form.non_field_errors }}
    </div>
  {% endif %}
  {% if isSuccess %}
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      Seus dados foram submetidos com sucesso. Eles serão validados pelos administradores
      e posteriormente será enviada uma confirmação por e-mail.
    </div>
  {% endif %}

  <form method="post" enctype="multipart/form-data" id="loginForm">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
      {{ field.label_tag }}
      {{ field }}
      {% if field.errors %}
      <ul class="list-group">
        {% for erro in field.errors %}
        <li class="list-group-item list-group-item-danger">{{ erro }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-default btn-lg">
      Cadastrar
    </button>
  </form>
  </div>
</div> <!-- /container -->

{% endblock %}

bernese/accounts/templates/register_validator.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container theme-showcase" role="main">
  <div class="jumbotron">
  {% if isErro or form.non_field_errors %}
  {% endif %}
  {% if isSuccess %}
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      Cadastro validado com sucesso.
    </div>
  {% else %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      Erro ao validar o cadastro.
    </div>
  {% endif %}
  </div>
</div> <!-- /container -->

{% endblock %}